# Generated by Django 5.1.1 on 2024-10-04 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('releaseDate', models.DateField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('watching', models.BooleanField(default=False)),
                ('watched', models.BooleanField(default=False)),
                ('inWishlist', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('movies', models.ManyToManyField(blank=True, to='movies.movie')),
            ],
        ),
    ]
