# Generated by Django 5.1.1 on 2024-09-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('lastWatched', models.DateTimeField()),
                ('finishedWatching', models.BooleanField()),
                ('numOfTimesWatched', models.IntegerField()),
                ('inWishList', models.BooleanField()),
            ],
        ),
    ]
