# Generated by Django 5.1.1 on 2024-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='numOfTimesWatched',
            field=models.PositiveIntegerField(),
        ),
    ]
