# Generated by Django 5.1.1 on 2024-09-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_numoftimeswatched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='finishedWatching',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='inWishList',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='lastWatched',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='numOfTimesWatched',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='releaseDate',
            field=models.DateField(blank=True),
        ),
    ]
