# Generated by Django 5.1.1 on 2024-12-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_releasedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='movies.movie'),
        ),
    ]
